#!/usr/bin/env python3
"""
Team Kenya — Viral Loops Campaign Configuration Script
=======================================================
Run this ONCE after creating your Viral Loops account to:
1. Verify API connectivity
2. Display campaign info
3. Test participant registration

Prerequisites:
- Create a Viral Loops account at https://viral-loops.com
- Choose the "Milestone Referral" template
- Configure 3 milestones in the dashboard:
    Milestone 1: 5 referrals  → "The Trailblazer" (Early Access + 10% Discount)
    Milestone 2: 10 referrals → "The Captain" (VIP Access + Exclusive Merch)
    Milestone 3: 15 referrals → "The Diaspora Champion" (Free Intl. Shipping + Badge)
- Copy your publicToken, apiToken, and campaignId from Installation settings

Usage:
    python3 configure_campaign.py --public-token YOUR_TOKEN --api-token YOUR_SECRET --campaign-id YOUR_ID
"""

import argparse
import json
import requests
import sys


def check_campaign(public_token: str, api_token: str, campaign_id: str):
    """Verify campaign exists and is accessible."""
    print("\n" + "=" * 60)
    print("  Team Kenya — Viral Loops Campaign Configuration")
    print("=" * 60)

    # 1. Get campaign stats
    print("\n[1/4] Checking campaign stats...")
    resp = requests.get(
        f"https://app.viral-loops.com/api/v3/campaign/stats",
        params={"campaignId": campaign_id},
        headers={"apiToken": api_token, "Accept": "application/json"}
    )
    if resp.status_code == 200:
        stats = resp.json()
        print(f"  ✅ Campaign accessible!")
        print(f"  Total participants: {stats.get('totalParticipants', 'N/A')}")
        print(f"  Total referrals: {stats.get('totalReferrals', 'N/A')}")
    else:
        print(f"  ❌ Failed: {resp.status_code} — {resp.text[:200]}")
        print("  Check your campaignId and apiToken")
        return False

    # 2. Get campaign info
    print("\n[2/4] Getting campaign info...")
    resp = requests.get(
        f"https://app.viral-loops.com/api/v3/campaign/info",
        params={"campaignId": campaign_id},
        headers={"apiToken": api_token, "Accept": "application/json"}
    )
    if resp.status_code == 200:
        info = resp.json()
        print(f"  ✅ Campaign info retrieved")
        print(f"  Campaign data: {json.dumps(info, indent=2)[:500]}")
    else:
        print(f"  ⚠️ Could not get campaign info: {resp.status_code}")

    # 3. Test participant registration (dry run)
    print("\n[3/4] Testing participant registration...")
    test_payload = {
        "publicToken": public_token,
        "user": {
            "firstname": "TestConfig",
            "email": "config-test@teamkenya-test.com",
            "extraData": {
                "location": "Kenya",
                "source": "configuration_test"
            }
        }
    }
    resp = requests.post(
        "https://app.viral-loops.com/api/v3/campaign/participant",
        json=test_payload,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
            "apiToken": api_token
        }
    )
    if resp.status_code == 200:
        result = resp.json()
        print(f"  ✅ Test participant registered!")
        print(f"  Referral code: {result.get('referralCode', 'N/A')}")
        print(f"  Is new: {result.get('isNew', 'N/A')}")
    else:
        print(f"  ❌ Registration failed: {resp.status_code} — {resp.text[:200]}")
        return False

    # 4. Generate .env file
    print("\n[4/4] Generating .env file...")
    env_content = f"""# Team Kenya — Viral Loops Integration Config
# Generated by configure_campaign.py

VL_PUBLIC_TOKEN={public_token}
VL_API_TOKEN={api_token}
VL_CAMPAIGN_ID={campaign_id}

TALLY_SIGNING_SECRET=
TALLY_API_KEY=tly-NAE1FQA1EzwErBBOdHqafgaIAkyhq3YI

HOST=0.0.0.0
PORT=8000
BASE_URL=https://your-deployment-domain.com

SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=info@replicadx.net
SMTP_PASSWORD=
"""
    with open("../.env", "w") as f:
        f.write(env_content)
    print(f"  ✅ .env file written!")

    print("\n" + "=" * 60)
    print("  ✅ CONFIGURATION COMPLETE")
    print("=" * 60)
    print(f"""
Next steps:
1. Configure milestones in Viral Loops dashboard:
   - Milestone 1: 5 referrals  → "The Trailblazer"
   - Milestone 2: 10 referrals → "The Captain"
   - Milestone 3: 15 referrals → "The Diaspora Champion"

2. Update .env with:
   - TALLY_SIGNING_SECRET (from Tally webhook settings)
   - SMTP_PASSWORD (for sending referral emails)
   - BASE_URL (your deployment domain)

3. Start the server:
   cd /home/ubuntu/viral_loops_integration
   python3 main.py

4. Configure Tally webhook:
   URL: https://your-domain.com/webhook/tally
   Method: POST

5. Add hidden field 'ref' to your Tally form for referral tracking
""")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Configure Team Kenya Viral Loops campaign")
    parser.add_argument("--public-token", required=True, help="Viral Loops public token")
    parser.add_argument("--api-token", required=True, help="Viral Loops secret API token")
    parser.add_argument("--campaign-id", required=True, help="Viral Loops campaign ID")
    args = parser.parse_args()

    success = check_campaign(args.public_token, args.api_token, args.campaign_id)
    sys.exit(0 if success else 1)
